name: MegaWalls
main: net.nuggetmc.mw.MegaWalls
version: 1.0
api-version: 1.16
author: HorseNuggets
commands:
  megawalls:
    description: The MegaWalls base command.
    usage: /mw
    aliases: [mw, class, kit]
  energy:
    description: Instant max energy (for debug).
    usage: /energy
    permission: mw.admin
    aliases: [e]
  debug:
    description: Parent debug command.
    usage: /debug
    permission: mw.admin
  mwinfo:
    description: MegaWalls class info command.
    usage: /mwinfo
    permission: mw.admin
  mwspawn:
    description: set spawn.
    usage: /mwspawn
    permission: mw.admin
  echest:
    description: see the echest of a player.
    usage: /echest
permissions:
  mw.*:
    description: MegaWalls parent permission.
    default: op
    children:
      mw.admin: true
  mw.admin:
    default: op